In [1]:
import os
import sys

import torch

if ".." not in sys.path:
    sys.path.insert(0, "..")

In [2]:
from datasets import OrganoidDataset
import pandas as pd
from os import path
import numpy as np

In [3]:
data = OrganoidDataset(data_dir='../data/organoids')

In [4]:
X,y = data.train

In [6]:
X.shape

(820733, 41)

In [7]:
y.shape

(820733, 2)

In [8]:
y.head()

cell_type  day
id                           
156737        Enterocyte    2
1151315             Tuft    7
611947   Enteroendocrine    3
756795            Goblet    6
213350        Enterocyte    2

In [10]:
from datasets import OrganoidDatasetDeprecated

data_dep = OrganoidDatasetDeprecated(data_dir='../data/organoids',device='cpu')

In [11]:
X_prev,y_prev = data_dep.train

In [17]:
np.equal(X_prev.numpy(),X).all()

True

In [19]:
data_caf = pd.read_pickle(path.join('../data/caf', 'Metadata_PDO_CAF_screening', 'Metadata_final_paper'))

In [20]:
rng = np.random.default_rng(seed=12345)
indices = rng.permutation(data_caf.shape[0])

In [22]:
data_caf.shape

(24756030, 54)

In [23]:
data_caf.head()

pHH3       RFP   mCHERRY  Vimentin       EpCAM       CK18      Pan_CK  \
0  1.444846  0.000000  0.000000  4.498622   66.200089  91.111916  161.084412   
1  5.783943  0.056214  0.434517  0.000000  190.450790   0.000000   17.851675   
2  1.165297  2.312362  0.357034  0.000000  266.436646   0.000000   42.965565   
3  0.000000  0.000000  0.000000  0.000000   84.960304  30.397985   56.991665   
4  0.498328  5.136724  0.000000  3.886348   48.076462   0.416286   30.709440   

          GFP        IdU      pPDK1  ...      Date  Patient  Culture  \
0  406.746246   4.811596  55.422546  ...  20211119        5      PDO   
1    0.000000   5.958662   4.794238  ...  20211119        5      PDO   
2    0.000000   0.000000   3.052261  ...  20211119        5      PDO   
3    0.000000   0.000000  15.021135  ...  20211119        5      PDO   
4    1.689452  28.263380  18.386526  ...  20211119        5      PDO   

   Treatment  Concentration  Replicate  Cell_type  pPKCa  Plate  Batch  
0          O              2          B       PDOs    NaN      O      2  
1          O              2          B       PDOs    NaN      O      2  
2          O              2          B       PDOs    NaN      O      2  
3          O              2          B       PDOs    NaN      O      2  
4          O              2          B       PDOs    NaN      O      2  

[5 rows x 54 columns]

In [28]:
data_caf.columns[:44]

Index(['pHH3', 'RFP', 'mCHERRY', 'Vimentin', 'EpCAM', 'CK18', 'Pan_CK', 'GFP',
       'IdU', 'pPDK1', 'cCaspase_3', 'Geminin', 'pMEK1_2', 'pNDRG',
       'pMKK4_SEK1', 'pBTK', 'pSRC', 'p4EBP1', 'pRB', 'pAKT308', 'pCREB',
       'pSMAD1_5_9', 'pAKT473', 'pNF_kB', 'pMKK3_MKK6', 'pP38', 'pMAPKAPK',
       'pAMPKa', 'pBAD', 'pHistone_H2A', 'p90RSK', 'pP120_catenin',
       'Beta_catenin_active', 'pGSK', 'pERK1_2', 'pSMAD2_3', 'PLK', 'CHGA',
       'pDNAPK', 'pS6', 'CD90', 'cPARP', 'pCHK1', 'Cyclin_B1'],
      dtype='object')

In [29]:
data_caf.columns[44:]

Index(['Date', 'Patient', 'Culture', 'Treatment', 'Concentration', 'Replicate',
       'Cell_type', 'pPKCa', 'Plate', 'Batch'],
      dtype='object')

In [31]:
rng = np.random.default_rng(seed=12345)
indices = rng.permutation(data_caf.shape[0])

train_n, val_n = int(data_caf.shape[0] * 0.7), int(data_caf.shape[0] * 0.2)
train_idx, val_idx, test_idx = indices[:train_n], indices[train_n:train_n + val_n], indices[train_n + val_n:]

In [34]:
data_caf.iloc[:,:44].to_numpy()

array([[1.44484627e+00, 0.00000000e+00, 0.00000000e+00, ...,
        1.88296829e+02, 5.28126373e+01, 3.61664200e+01],
       [5.78394270e+00, 5.62137887e-02, 4.34517384e-01, ...,
        4.31224785e+01, 1.56797457e+01, 7.03363113e+01],
       [1.16529655e+00, 2.31236172e+00, 3.57033521e-01, ...,
        2.92459686e+02, 3.91039886e+01, 6.69027939e+01],
       ...,
       [0.00000000e+00, 2.51099691e-02, 5.98175240e+00, ...,
        5.24205065e+00, 3.31141586e+01, 1.12272156e+02],
       [1.07582264e+01, 0.00000000e+00, 7.71155024e+00, ...,
        2.03852253e+01, 4.51682167e+01, 9.40149918e+01],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
        1.98212814e+00, 9.82693672e+00, 3.13391228e+01]])

In [2]:
from datasets import CafDataset

In [3]:
data = CafDataset(data_dir='../data/caf')

In [4]:
X,y = data.train

In [11]:
y.reset_index()

index      Date Patient Culture Treatment Concentration  \
0         23799121  20210610     216     PDO       CSF             4   
1         12586350  20210330      27     PDO         V             1   
2         13553784  20210602      99    PDOF      DMSO             0   
3         13251389  20210427     141       F         V             1   
4         16469786  20210413      21       F         F             4   
...            ...       ...     ...     ...       ...           ...   
17329216   9019234  20210518       5       F         L             4   
17329217   6471919  20210602      99     PDO        VS             4   
17329218   3870897  20210330      27       F         S             3   
17329219  11185988  20210317      23    PDOF         L             1   
17329220  21413623  20210607      11       F        SF             3   

         Replicate Cell_type      pPKCa Plate  Batch  
0                C      PDOs   0.000000   CSF      1  
1                B      PDOs        NaN   SLV      1  
2                B      Fibs  34.628689   SLV      1  
3                A      Fibs        NaN   SLV      1  
4                B      Fibs        NaN   CSF      1  
...            ...       ...        ...   ...    ...  
17329216         B      Fibs   8.634648   SLV      1  
17329217         B      PDOs   6.938818   SLV      1  
17329218         A      Fibs        NaN   SLV      1  
17329219         A      Fibs        NaN   SLV      1  
17329220         C      Fibs  22.096056   CSF      1  

[17329221 rows x 11 columns]

In [13]:
X

array([[0.00000000e+00, 0.00000000e+00, 3.61259460e-01, ...,
        8.22187119e+01, 6.55629395e+02, 2.39033310e+02],
       [0.00000000e+00, 1.18359785e+01, 1.42496994e+02, ...,
        0.00000000e+00, 3.22506104e+01, 1.14379997e+02],
       [1.61246071e+01, 2.82575321e+00, 0.00000000e+00, ...,
        4.18170471e+01, 7.88884033e+02, 1.81745949e+01],
       ...,
       [3.40721059e+00, 1.01839137e+00, 0.00000000e+00, ...,
        1.91872444e+01, 1.44982269e+02, 3.82487297e+01],
       [0.00000000e+00, 0.00000000e+00, 5.87199628e-01, ...,
        2.04344730e+01, 2.98615761e+01, 3.99017143e+01],
       [0.00000000e+00, 3.49280596e+00, 9.65314102e+00, ...,
        0.00000000e+00, 4.34025421e+01, 0.00000000e+00]])

In [17]:
data_dir = "../data/breast_cancer_challenge/"

In [27]:
import glob

filenames = glob.glob(data_dir+"*.csv")

In [24]:
dfs = [pd.read_csv(filename) for filename in filenames]

In [25]:
dfs[0]

treatment cell_line  time  cellID  fileID  b.CATENIN  cleavedCas  \
0            EGF     BT549   0.0       1    3477   1.606709    2.497635   
1            EGF     BT549   0.0       2    3477   1.514057    2.586081   
2            EGF     BT549   0.0       3    3477   0.386000    3.572410   
3            EGF     BT549   0.0       4    3477   1.482330    3.614918   
4            EGF     BT549   0.0       5    3477   1.458379    2.639350   
...          ...       ...   ...     ...     ...        ...         ...   
303654      iPKC     BT549  60.0    2251    3535   0.651636    3.026354   
303655      iPKC     BT549  60.0    2252    3535   0.624960    4.060094   
303656      iPKC     BT549  60.0    2253    3535   0.346863    1.987712   
303657      iPKC     BT549  60.0    2254    3535   0.325139    1.572446   
303658      iPKC     BT549  60.0    2255    3535   0.723166    1.989624   

        CyclinB     GAPDH       IdU  ...   p.PDPK1  p.PLCg2     p.RB     p.S6  \
0       3.80664  2.532803   9.66314  ...  1.818946      NaN  2.84637  8.28681   
1       5.93075  1.846320  13.01940  ...  0.572443      NaN  3.74439  8.28212   
2       6.96979  3.117471   7.10625  ...  0.516309      NaN  3.11308  5.20016   
3       3.98046  2.212820   5.52471  ...  0.543217      NaN  4.59136  4.43111   
4       7.80703  4.087035   6.86747  ...  0.516309      NaN  6.17801  8.51356   
...         ...       ...       ...  ...       ...      ...      ...      ...   
303654  4.00420  0.759907  11.16097  ...  0.944456      NaN  3.17220  6.15738   
303655  6.13596  3.189131  11.60115  ...  1.605182      NaN  4.17209  8.72054   
303656  2.64232  1.584982   4.77368  ...  1.343414      NaN  2.35439  5.00121   
303657  2.08338  1.276758   6.09144  ...  0.516309      NaN  2.20794  5.87649   
303658  6.49736  0.565534   5.92258  ...  0.516309      NaN  3.88352  6.89788   

           p.S6K  p.SMAD23     p.SRC   p.STAT1   p.STAT3   p.STAT5  
0       2.298567  3.128208  2.210724  3.478755  2.769994  2.154990  
1       1.582917  3.252946  1.107239  3.331805  4.180568  1.945807  
2       2.444143  4.014149  2.853183  3.666968  3.791345  3.103875  
3       1.557999  2.506928  1.846837  3.026639  3.489565  2.590569  
4       3.000138  3.541025  3.030370  4.869474  3.827781  3.361050  
...          ...       ...       ...       ...       ...       ...  
303654  1.356142  2.605012  2.517724  4.156714  2.587026  3.147370  
303655  3.116203  3.675474  2.611052  3.984568  4.024100  3.053903  
303656  0.633670  0.952564  2.082346  2.630983  0.928161  2.463751  
303657  0.790988  2.099592  1.929522  3.443698  1.762933  1.969557  
303658  1.278064  2.409719  1.694329  3.375054  1.589591  3.034540  

[303659 rows x 42 columns]

In [29]:
data = pd.concat(dfs)

In [33]:
data

treatment cell_line  time  cellID  fileID  b.CATENIN  cleavedCas  \
0            EGF     BT549   0.0       1    3477   1.606709    2.497635   
1            EGF     BT549   0.0       2    3477   1.514057    2.586081   
2            EGF     BT549   0.0       3    3477   0.386000    3.572410   
3            EGF     BT549   0.0       4    3477   1.482330    3.614918   
4            EGF     BT549   0.0       5    3477   1.458379    2.639350   
...          ...       ...   ...     ...     ...        ...         ...   
439183      iPKC  MDAMB453  60.0    9931    3057   0.796624    0.985459   
439184      iPKC  MDAMB453  60.0    9932    3057   0.796624    0.760968   
439185      iPKC  MDAMB453  60.0    9933    3057   1.792894    3.005336   
439186      iPKC  MDAMB453  60.0    9934    3057   0.796624    2.043958   
439187      iPKC  MDAMB453  60.0    9935    3057   0.796624    1.604966   

         CyclinB     GAPDH       IdU  ...   p.PDPK1   p.PLCg2     p.RB  \
0       3.806640  2.532803   9.66314  ...  1.818946       NaN  2.84637   
1       5.930750  1.846320  13.01940  ...  0.572443       NaN  3.74439   
2       6.969790  3.117471   7.10625  ...  0.516309       NaN  3.11308   
3       3.980460  2.212820   5.52471  ...  0.543217       NaN  4.59136   
4       7.807030  4.087035   6.86747  ...  0.516309       NaN  6.17801   
...          ...       ...       ...  ...       ...       ...      ...   
439183  2.386117  2.800958   6.43220  ...  1.721783  1.649587  1.65488   
439184  0.733187  0.654867   4.42999  ...  0.136632  0.814841  2.94198   
439185  0.886315  3.143383   5.88008  ...  1.740662  1.192765  4.45737   
439186  1.749193  2.004873   4.36651  ...  1.918299  0.950457  3.51759   
439187  2.689533  3.112336   4.36651  ...  2.384222  0.358041  1.65488   

           p.S6     p.S6K  p.SMAD23     p.SRC   p.STAT1   p.STAT3   p.STAT5  
0       8.28681  2.298567  3.128208  2.210724  3.478755  2.769994  2.154990  
1       8.28212  1.582917  3.252946  1.107239  3.331805  4.180568  1.945807  
2       5.20016  2.444143  4.014149  2.853183  3.666968  3.791345  3.103875  
3       4.43111  1.557999  2.506928  1.846837  3.026639  3.489565  2.590569  
4       8.51356  3.000138  3.541025  3.030370  4.869474  3.827781  3.361050  
...         ...       ...       ...       ...       ...       ...       ...  
439183  5.78805  2.060610  1.116810  0.900235  1.798180  0.323054  2.071620  
439184  2.33690  1.168810 -0.015309  1.684120  1.271067  0.323054 -0.170062  
439185  3.59849  1.304170  1.982740  1.853280  3.161774  1.430336  0.866602  
439186  4.27009  1.690850  2.151830  1.532070  3.373595  0.437448  1.036730  
439187  4.57038  2.573030  2.235580  2.270560  4.901324  0.323054  2.231986  

[17126329 rows x 42 columns]

In [34]:
print(data.isna().sum())

treatment              0
cell_line              0
time                   0
cellID                 0
fileID                 0
b.CATENIN              0
cleavedCas             0
CyclinB                0
GAPDH                  0
IdU                    0
Ki.67                  0
p.4EBP1                0
p.Akt.Ser473.          0
p.AKT.Thr308.          0
p.AMPK                 0
p.BTK                  0
p.CREB                 0
p.ERK                  0
p.FAK                  0
p.GSK3b                0
p.H3                   0
p.HER2           4157637
p.JNK                  0
p.MAP2K3               0
p.MAPKAPK2             0
p.MEK                  0
p.MKK3.MKK6            0
p.MKK4                 0
p.NFkB                 0
p.p38                  0
p.p53                  0
p.p90RSK               0
p.PDPK1                0
p.PLCg2          1946351
p.RB                   0
p.S6                   0
p.S6K                  0
p.SMAD23               0
p.SRC                  0
p.STAT1                0


In [42]:
data.iloc[data.isna().any(axis=1).to_numpy()].cell_line.unique()

array(['BT549', 'HCC1954', 'MDAkb2', 'HCC1419', 'HCC38', 'HCC70',
       'HCC1395', 'T47D', 'HCC1937', 'HCC1187', 'HCC1569', 'MDAMB361',
       'MDAMB134VI', 'HCC1500', 'UACC893', 'MDAMB453'], dtype=object)

In [43]:
data.columns

Index(['treatment', 'cell_line', 'time', 'cellID', 'fileID', 'b.CATENIN',
       'cleavedCas', 'CyclinB', 'GAPDH', 'IdU', 'Ki.67', 'p.4EBP1',
       'p.Akt.Ser473.', 'p.AKT.Thr308.', 'p.AMPK', 'p.BTK', 'p.CREB', 'p.ERK',
       'p.FAK', 'p.GSK3b', 'p.H3', 'p.HER2', 'p.JNK', 'p.MAP2K3', 'p.MAPKAPK2',
       'p.MEK', 'p.MKK3.MKK6', 'p.MKK4', 'p.NFkB', 'p.p38', 'p.p53',
       'p.p90RSK', 'p.PDPK1', 'p.PLCg2', 'p.RB', 'p.S6', 'p.S6K', 'p.SMAD23',
       'p.SRC', 'p.STAT1', 'p.STAT3', 'p.STAT5'],
      dtype='object')

In [44]:
data.columns[:5]

Index(['treatment', 'cell_line', 'time', 'cellID', 'fileID'], dtype='object')

In [47]:
data.columns[5:]

Index(['b.CATENIN', 'cleavedCas', 'CyclinB', 'GAPDH', 'IdU', 'Ki.67',
       'p.4EBP1', 'p.Akt.Ser473.', 'p.AKT.Thr308.', 'p.AMPK', 'p.BTK',
       'p.CREB', 'p.ERK', 'p.FAK', 'p.GSK3b', 'p.H3', 'p.HER2', 'p.JNK',
       'p.MAP2K3', 'p.MAPKAPK2', 'p.MEK', 'p.MKK3.MKK6', 'p.MKK4', 'p.NFkB',
       'p.p38', 'p.p53', 'p.p90RSK', 'p.PDPK1', 'p.PLCg2', 'p.RB', 'p.S6',
       'p.S6K', 'p.SMAD23', 'p.SRC', 'p.STAT1', 'p.STAT3', 'p.STAT5'],
      dtype='object')

In [48]:
data.dropna()

treatment cell_line  time  cellID  fileID  b.CATENIN  cleavedCas  \
0            EGF      BT20   0.0       1     173   1.473732    3.442083   
1            EGF      BT20   0.0       1     209   1.711831    2.508931   
2            EGF      BT20   0.0       2     173   1.491148    1.978159   
3            EGF      BT20   0.0       2     209   1.250936    2.395486   
4            EGF      BT20   0.0       3     173   1.498227    4.024200   
...          ...       ...   ...     ...     ...        ...         ...   
242943      iPKC    CAL148  60.0    9531    1784   0.377909    2.342130   
242944      iPKC    CAL148  60.0    9532    1784   0.890460    0.898342   
242945      iPKC    CAL148  60.0    9533    1784   0.999780    2.874888   
242946      iPKC    CAL148  60.0    9534    1784   1.177386    3.353795   
242947      iPKC    CAL148  60.0    9535    1784   1.360019    2.409274   

        CyclinB     GAPDH       IdU  ...   p.PDPK1   p.PLCg2     p.RB  \
0       1.53231  3.154426   4.25020  ...  1.933920  3.557209  3.53145   
1       1.20489  2.798322   5.46877  ...  1.685958  3.373101  2.70542   
2       2.61173  3.190067   4.86440  ...  0.859948  1.492517  5.25069   
3       2.14984  1.170383   5.06905  ...  0.516309  0.986227  4.89048   
4       3.28279  3.432561   6.24600  ...  2.179873  4.171272  6.53057   
...         ...       ...       ...  ...       ...       ...      ...   
242943  2.92017  3.831750   5.72884  ...  3.004839  4.208258  2.61904   
242944  3.21465  3.752526  11.77937  ...  1.778866  2.013538  2.20794   
242945  2.57836  4.552094   4.25020  ...  3.408850  4.219160  3.55132   
242946  2.39450  3.778470   5.42498  ...  2.334015  1.004381  2.35089   
242947  1.20489  3.329338   4.25020  ...  2.686500  3.944519  3.10293   

           p.S6     p.S6K  p.SMAD23     p.SRC   p.STAT1   p.STAT3   p.STAT5  
0       4.46999  2.019960  2.416691  3.938022  3.128716  2.849716  2.469874  
1       5.04671  2.741856  2.169223  3.275558  2.822612  1.347548  2.795694  
2       6.34630  1.530206  2.406163  1.790347  3.593621  1.886075  2.460457  
3       3.05252  2.442806  3.053240  0.799536  1.736163  3.207189  1.774129  
4       7.41896  3.626556  3.356824  3.375600  2.977972  2.687300  2.972260  
...         ...       ...       ...       ...       ...       ...       ...  
242943  5.63935  3.196760  2.629449  4.091201  3.268736  2.272096  2.002150  
242944  7.03941  3.039361  1.933805  3.211653  3.542337  1.872235  2.848350  
242945  7.84043  2.892824  1.868630  3.805336  3.277699  0.652426  2.363650  
242946  6.50466  2.272950  0.904632  1.908195  2.851001  1.864566  1.657300  
242947  3.38994  2.403584  1.973524  2.308421  2.623940  2.163171  1.742350  

[11022341 rows x 42 columns]

In [1]:
import sys

if ".." not in sys.path:
    sys.path.insert(0, "..")

In [2]:
from datasets import OrganoidDataset, ChallengeDataset, CafDataset

In [3]:
data = OrganoidDataset(data_dir='../data/organoids')

In [5]:
X,y = data.train

In [6]:
X

array([[0.        , 4.104063  , 3.523024  , ..., 0.        , 3.8881786 ,
        6.389593  ],
       [0.        , 3.2745147 , 1.7237808 , ..., 2.686204  , 0.90823185,
        5.908281  ],
       [0.        , 4.236786  , 2.9206614 , ..., 5.5366745 , 3.148032  ,
        6.711488  ],
       ...,
       [0.        , 1.8122448 , 2.4643033 , ..., 1.8104887 , 2.2688913 ,
        0.10865887],
       [0.        , 3.604407  , 1.7619798 , ..., 4.697796  , 3.2597408 ,
        6.089817  ],
       [0.        , 3.9847968 , 2.483168  , ..., 0.        , 0.        ,
        5.4630876 ]], dtype=float32)

In [5]:
y

index        cell_type  day
0        156737       Enterocyte    2
1       1151315             Tuft    7
2        611947  Enteroendocrine    3
3        756795           Goblet    6
4        213350       Enterocyte    2
...         ...              ...  ...
820728     2685       Enterocyte    1
820729  1122479             Tuft    5
820730   253852       Enterocyte    3
820731   746001           Goblet    5
820732   198014       Enterocyte    2

[820733 rows x 3 columns]

In [11]:
data = ChallengeDataset(data_dir='../data/breast_cancer_challenge/')

In [4]:
X,y = data.train

In [5]:
X.shape

(7715638, 37)

In [6]:
X.dtype

dtype('float32')

In [7]:
X

array([[1.305508 , 2.079029 , 2.77041  , ..., 2.7504065, 0.738451 ,
        2.426468 ],
       [0.861563 , 3.167372 , 2.99853  , ..., 3.0209234, 2.189962 ,
        2.7098024],
       [0.996941 , 3.403287 , 3.50676  , ..., 3.75957  , 2.743454 ,
        2.76213  ],
       ...,
       [1.005257 , 2.64963  , 4.3092   , ..., 1.8417668, 0.652426 ,
        2.38526  ],
       [0.543132 , 0.898342 , 1.20489  , ..., 4.2914376, 1.326958 ,
        1.9774158],
       [0.454128 , 2.849456 , 1.88377  , ..., 2.8662198, 2.78903  ,
        2.9398377]], dtype=float32)

In [13]:
y

index treatment cell_line  time  cellID  fileID
0         215104     iEGFR    MCF10A   7.0    9428     807
1         202234     iPI3K   HCC1500   0.0    5177    3212
2          94036       EGF     HCC70  13.0   11573    3601
3         318186      iMEK     HCC70   9.0    2399    3615
4         301194      iMEK     HCC70   7.0    1491    3643
...          ...       ...       ...   ...     ...     ...
11988425  241199     iPI3K  MDAMB415   0.0    1495     248
11988426   68862       EGF       MX1  13.0    7616    2854
11988427  121106     iEGFR   HCC1954   9.0    4614    3519
11988428  190906       EGF     OCUBM   0.0   11730    2472
11988429   71195       EGF       MX1  13.0    9949    2854

[11988430 rows x 6 columns]

In [2]:
import sys
if ".." not in sys.path:
    sys.path.insert(0, "..")

from datasets import OrganoidDataset
data = OrganoidDataset(data_dir='../data/organoids/')

In [3]:
X,y = data.train

In [4]:
print(X.shape)
print(X.dtype)
X

(820733, 41)
float32


array([[0.        , 4.104063  , 3.523024  , ..., 0.        , 3.8881786 ,
        6.389593  ],
       [0.        , 3.2745147 , 1.7237808 , ..., 2.686204  , 0.90823185,
        5.908281  ],
       [0.        , 4.236786  , 2.9206614 , ..., 5.5366745 , 3.148032  ,
        6.711488  ],
       ...,
       [0.        , 1.8122448 , 2.4643033 , ..., 1.8104887 , 2.2688913 ,
        0.10865887],
       [0.        , 3.604407  , 1.7619798 , ..., 4.697796  , 3.2597408 ,
        6.089817  ],
       [0.        , 3.9847968 , 2.483168  , ..., 0.        , 0.        ,
        5.4630876 ]], dtype=float32)

In [10]:
from torch.utils.data import TensorDataset
import torch
X[:X.shape[0] // 1024 *1024].reshape((-1,1024,X.shape[1])).shape

(801, 1024, 41)

In [6]:
import ray
ray.shutdown()
ray.init()

2023-02-03 23:01:50,171	INFO worker.py:1538 -- Started a local Ray instance.


RayContext(dashboard_url='', python_version='3.10.6', ray_version='2.2.0', ray_commit='b6af0887ee5f2e460202133791ad941a41f15beb', address_info={'node_ip_address': '192.168.2.11', 'raylet_ip_address': '192.168.2.11', 'redis_address': None, 'object_store_address': '/tmp/ray/session_2023-02-03_23-01-48_373375_1080370/sockets/plasma_store', 'raylet_socket_name': '/tmp/ray/session_2023-02-03_23-01-48_373375_1080370/sockets/raylet', 'webui_url': '', 'session_dir': '/tmp/ray/session_2023-02-03_23-01-48_373375_1080370', 'metrics_export_port': 54892, 'gcs_address': '192.168.2.11:65002', 'address': '192.168.2.11:65002', 'dashboard_agent_listen_port': 52365, 'node_id': '4012e4cb6ef5f6f281a8e23716156b3f37ec998d2dacebf3eeaf20c8'})

In [12]:
ds = ray.data.from_numpy(X[:X.shape[0] // 1024 *1024].reshape((-1,1024,X.shape[1])))

In [13]:
for batch in ds.iter_torch_batches():
    print(batch.shape)
    print(batch)
    break

torch.Size([256, 1024, 41])
tensor([[[0.0000, 4.1041, 3.5230,  ..., 0.0000, 3.8882, 6.3896],
         [0.0000, 3.2745, 1.7238,  ..., 2.6862, 0.9082, 5.9083],
         [0.0000, 4.2368, 2.9207,  ..., 5.5367, 3.1480, 6.7115],
         ...,
         [0.0000, 4.2606, 2.5510,  ..., 0.0000, 2.4632, 6.0600],
         [0.0000, 2.7392, 2.6043,  ..., 0.0000, 3.6093, 3.8802],
         [0.0000, 3.1756, 1.6602,  ..., 4.2140, 2.3501, 6.0158]],

        [[0.0000, 4.7434, 4.2539,  ..., 0.0000, 4.2112, 5.6827],
         [0.4333, 3.1787, 4.4757,  ..., 0.0000, 3.0614, 7.0806],
         [0.0000, 4.7153, 2.2860,  ..., 1.6890, 0.4364, 4.4237],
         ...,
         [0.0000, 3.4355, 4.1664,  ..., 0.0000, 4.6436, 4.1922],
         [0.0000, 2.3814, 4.4285,  ..., 2.5050, 3.2064, 7.2450],
         [0.0000, 4.9156, 3.2758,  ..., 2.3066, 4.2252, 5.7855]],

        [[0.1593, 3.3300, 3.8487,  ..., 2.2483, 2.0702, 0.0000],
         [0.0000, 4.4584, 3.4592,  ..., 2.8349, 3.1095, 5.4611],
         [0.0000, 1.9933, 1.22