In [1]:
from datasets import OrganoidDataset
data = OrganoidDataset(device='cpu')
X_train,y_train = data.train
X_val,y_val = data.val

/home/egor/PycharmProjects/deep_dr/venv/lib/python3.10/site-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: libtorch_cuda_cu.so: cannot open shared object file: No such file or directory
  warn(f"Failed to load image Python extension: {e}")


In [6]:
from sklearn.decomposition import PCA
import numpy as np
pca = PCA(n_components=41)
pca.fit(X_train)
pca.singular_values_

array([4016.83391857, 2900.22864727, 1631.77281833, 1453.1489101 ,
       1180.22991813, 1117.22008742, 1038.5007746 ,  975.09200091,
        924.97633661,  888.3189539 ,  837.00696837,  821.18841104,
        798.5864352 ,  784.84955287,  756.7588344 ,  739.96582703,
        724.45973982,  698.91690709,  646.56897628,  634.51777384,
        608.83572719,  552.83887982,  546.25836983,  527.13630821,
        497.33003203,  489.93083956,  478.30039399,  469.99107165,
        462.21112411,  452.45185965,  442.451303  ,  432.27875179,
        424.97438164,  421.46488258,  417.78623225,  393.50336161,
        374.67083741,  369.87259781,  349.451937  ,  338.13250631,
        316.84362665])

In [24]:
from torch.nn import functional as F
import torch

res = []
for i in range(41):
    reduced_dim = np.pad(pca.transform(X_val)[:,:i],((0,0),(0,41-i)))
    loss = F.mse_loss(X_val, torch.from_numpy(pca.inverse_transform(reduced_dim)))
    print(f"Components: {i}, MSE:{loss}")
    res.append({"Components":i,'MSE':loss.item()})

Components: 0, MSE:1.3534091070398027
Components: 1, MSE:0.8742205681680011
Components: 2, MSE:0.6241996179403656
Components: 3, MSE:0.5448696982699932
Components: 4, MSE:0.48213736912791155
Components: 5, MSE:0.4407109988359521
Components: 6, MSE:0.4035925440524936
Components: 7, MSE:0.37159963458265155
Components: 8, MSE:0.3433167767174395
Components: 9, MSE:0.31781336369003815
Components: 10, MSE:0.2941713658236005
Components: 11, MSE:0.2733737155973865
Components: 12, MSE:0.25328771939011835
Components: 13, MSE:0.23423279107156517
Components: 14, MSE:0.21594383071086085
Components: 15, MSE:0.19876837079506549
Components: 16, MSE:0.18238216478572516
Components: 17, MSE:0.1666925200018777
Components: 18, MSE:0.15212095765613814
Components: 19, MSE:0.1397030598215791
Components: 20, MSE:0.1277308667978653
Components: 21, MSE:0.11674789356275649
Components: 22, MSE:0.10764614411218067
Components: 23, MSE:0.09872408977275896
Components: 24, MSE:0.09047309627193215
Components: 25, MSE:0.

In [25]:
import altair as alt
import pandas as pd
pd.DataFrame(res).head()

Components       MSE
0           0  1.353409
1           1  0.874221
2           2  0.624200
3           3  0.544870
4           4  0.482137

In [26]:
alt.Chart(pd.DataFrame(res)).mark_bar().encode(
    x='Components:O',
    y=alt.Y(
        "MSE:Q",
        scale=alt.Scale(type="log"),
    )
).properties(width=600)

/home/egor/PycharmProjects/deep_dr/venv/lib/python3.10/site-packages/altair/utils/core.py:317: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  for col_name, dtype in df.dtypes.iteritems():


alt.Chart(...)

In [27]:
alt.Chart(pd.DataFrame(res)).mark_bar().encode(
    x='Components:O',
    y=alt.Y(
        "MSE:Q",
    )
).properties(width=600)

/home/egor/PycharmProjects/deep_dr/venv/lib/python3.10/site-packages/altair/utils/core.py:317: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  for col_name, dtype in df.dtypes.iteritems():


alt.Chart(...)

In [4]:
import sys
if ".." not in sys.path:
    sys.path.insert(0, "..")

from datasets import CafDataset
data = CafDataset(data_dir='../data/caf/')
X_train,y_train = data.train
X_val,y_val = data.val

In [5]:
from sklearn.decomposition import PCA
import numpy as np
pca = PCA(n_components=44)
pca.fit(X_train)
pca.singular_values_

array([20259.254 , 16604.53  ,  9124.931 ,  7975.14  ,  7125.786 ,
        6335.76  ,  6199.879 ,  5768.3047,  5380.271 ,  5286.507 ,
        5165.567 ,  5072.233 ,  4957.979 ,  4933.247 ,  4783.9487,
        4550.519 ,  4485.4194,  4197.748 ,  4076.226 ,  3918.9438,
        3724.5315,  3444.5537,  3359.0325,  3104.1387,  3021.807 ,
        2959.9167,  2913.94  ,  2795.4778,  2720.2344,  2699.0483,
        2619.7495,  2572.1458,  2521.712 ,  2481.8972,  2441.5217,
        2392.0176,  2334.9666,  2281.1448,  2195.7217,  2168.2996,
        2116.6824,  1991.6777,  1703.83  ,  1685.267 ], dtype=float32)

In [7]:
from torch.nn import functional as F
import torch

res = []
for i in range(44):
    reduced_dim = np.pad(pca.transform(X_val)[:,:i],((0,0),(0,44-i)))
    loss = F.mse_loss(torch.from_numpy(X_val), torch.from_numpy(pca.inverse_transform(reduced_dim)))
    print(f"Components: {i}, MSE:{loss}")
    res.append({"Components":i,'MSE':loss.item()})

Components: 0, MSE:1.8818624019622803
Components: 1, MSE:1.343815565109253
Components: 2, MSE:0.9819348454475403
Components: 3, MSE:0.8728591203689575
Components: 4, MSE:0.789380669593811
Components: 5, MSE:0.7227479219436646
Components: 6, MSE:0.6700727939605713
Components: 7, MSE:0.6196869611740112
Components: 8, MSE:0.5760135054588318
Components: 9, MSE:0.5380264520645142
Components: 10, MSE:0.5013865232467651
Components: 11, MSE:0.4663931131362915
Components: 12, MSE:0.43259817361831665
Components: 13, MSE:0.4003489911556244
Components: 14, MSE:0.3684535026550293
Components: 15, MSE:0.3384431302547455
Components: 16, MSE:0.31126919388771057
Components: 17, MSE:0.2848964035511017
Components: 18, MSE:0.26180410385131836
Components: 19, MSE:0.23999106884002686
Components: 20, MSE:0.2198437601327896
Components: 21, MSE:0.20165282487869263
Components: 22, MSE:0.18609344959259033
Components: 23, MSE:0.1713021844625473
Components: 24, MSE:0.15865914523601532
Components: 25, MSE:0.14668010

In [8]:
from datasets import ChallengeDataset
data = ChallengeDataset(data_dir='../data/breast_cancer_challenge/')
X_train,y_train = data.train
X_val,y_val = data.val

In [9]:
from sklearn.decomposition import PCA
import numpy as np
pca = PCA(n_components=37)
pca.fit(X_train)
pca.singular_values_

array([10828.17  ,  7165.361 ,  5013.435 ,  3885.605 ,  3584.163 ,
        3396.6348,  3154.4314,  2975.5515,  2901.534 ,  2725.0376,
        2516.2737,  2426.4995,  2363.5513,  2327.261 ,  2188.9778,
        2133.354 ,  2060.583 ,  1953.6179,  1869.5284,  1826.6351,
        1803.9641,  1742.966 ,  1714.7451,  1684.3162,  1660.2667,
        1619.6733,  1607.3462,  1586.5559,  1552.2286,  1513.2927,
        1456.4614,  1427.4927,  1384.9562,  1362.1127,  1327.2257,
        1252.7627,  1072.9457], dtype=float32)

In [10]:
from torch.nn import functional as F
import torch

res = []
for i in range(37):
    reduced_dim = np.pad(pca.transform(X_val)[:,:i],((0,0),(0,37-i)))
    loss = F.mse_loss(torch.from_numpy(X_val), torch.from_numpy(pca.inverse_transform(reduced_dim)))
    print(f"Components: {i}, MSE:{loss}")
    res.append({"Components":i,'MSE':loss.item()})

Components: 0, MSE:1.24342679977417
Components: 1, MSE:0.8327886462211609
Components: 2, MSE:0.6527276635169983
Components: 3, MSE:0.5648074150085449
Components: 4, MSE:0.511974573135376
Components: 5, MSE:0.46691030263900757
Components: 6, MSE:0.4266059994697571
Components: 7, MSE:0.39171257615089417
Components: 8, MSE:0.3607211410999298
Components: 9, MSE:0.3312135934829712
Components: 10, MSE:0.30524471402168274
Components: 11, MSE:0.2830720841884613
Components: 12, MSE:0.26243868470191956
Components: 13, MSE:0.24285125732421875
Components: 14, MSE:0.22392109036445618
Components: 15, MSE:0.20713099837303162
Components: 16, MSE:0.19115370512008667
Components: 17, MSE:0.17627164721488953
Components: 18, MSE:0.16289520263671875
Components: 19, MSE:0.15064789354801178
Components: 20, MSE:0.13893915712833405
Components: 21, MSE:0.1275463104248047
Components: 22, MSE:0.11687116324901581
Components: 23, MSE:0.10654953122138977
Components: 24, MSE:0.09661940485239029
Components: 25, MSE:0.0